# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0002_auto_20170408_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='score',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
