# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0002_auto_20170408_1003'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Info')),
            ],
        ),
    ]
